name: Python CI with Auto Docs

on: [push, pull_request]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run unit tests
      run: |
        python -m pytest tests/ -v
        
    - name: Run with coverage
      run: |
        pip install pytest-cov
        python -m pytest tests/ --cov=src --cov-report=term-missing
        
    - name: Update README automatically
      run: |
        python scripts/generate_docs.py
        
    - name: Commit updated README
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Auto-update README.md"
        file_pattern: README.md
        commit_user_name: "github-actions[bot]"
        commit_user_email: "github-actions[bot]@users.noreply.github.com"
