name: Python CI with Auto Docs

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run unit tests
      run: |
        python -m pytest tests/ -v
        
    # НОВЫЙ ШАГ: Автообновление README.md
    - name: Update README automatically
      run: |
        python scripts/update_readme.py
        
    - name: Commit updated README
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add README.md
        git diff --staged --quiet || git commit -m "Auto-update README.md"
        git push
