name: Python CI with Auto Docs

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run unit tests
      run: |
        python -m pytest tests/ -v
        
    - name: Run with coverage
      run: |
        pip install pytest-cov
        python -m pytest tests/ --cov=src --cov-report=term-missing
        
    - name: Update README automatically
      run: |
        python scripts/generate_docs.py
        echo "README updated locally. Manual commit required for persistent changes."
        
    - name: Show update status
      run: |
        echo "Documentation generated successfully"
        echo "Check README.md for changes"
        echo "Manual commit needed to save changes permanently"
